import IPB_Amel from "../public/assets/documentation/graduation/IPB_Amel_2.jpg";

export const eventPhotos = [
  {
    src: require("/public/assets/documentation/event/D3_perhotelan_goes_to_bali.jpg"),
    width: 6,
    height: 5,
    title: "D3 Perhotelan Goes To Bali",
  },
  {
    src: require("/public/assets/documentation/event/D3_perhotelan_goes_to_bali_2.jpg"),
    width: 3,
    height: 3,
    title: "D3 Perhotelan Goes To Bali",
  },
  {
    src: require("/public/assets/documentation/event/dalawampu_2022.jpg"),
    width: 3,
    height: 2,
    title: "Dalawampu 2022",
  },
  {
    src: require("/public/assets/documentation/event/dalawampu_2022_2.jpg"),
    width: 3,
    height: 2,
    title: "Dalawampu 2022",
  },
  {
    src: require("/public/assets/documentation/event/dalawampu_2022_3.jpg"),
    width: 3,
    height: 2,
    title: "Dalawampu 2022",
  },
  {
    src: require("/public/assets/documentation/event/dalawampu_2022_4.jpg"),
    width: 3,
    height: 2,
    title: "Dalawampu 2022",
  },
  {
    src: require("/public/assets/documentation/event/family_gathering_sbdit_3_TPPU_bareskrim_polri.jpg"),
    width: 3,
    height: 2,
    title: "Family Gathering SBDIT 3 TPPU Bareskrim Polri",
  },
  {
    src: require("/public/assets/documentation/event/peresmian_jln_prof_mochtar_kusumaatmadja.jpg"),
    width: 2,
    height: 3,
    title: "Peresmian Jln. Prof Mochtar Kusumaatmadja",
  },
  {
    src: require("/public/assets/documentation/event/family_gathering_sbdit_3_TPPU_bareskrim_polri_2.jpg"),
    width: 3,
    height: 2,
    title: "Family Gathering SBDIT 3 TPPU Bareskrim Polri",
  },
  {
    src: require("/public/assets/documentation/event/graduation_ceremony_pribadi_bilingual_school.jpg"),
    width: 3,
    height: 2,
    title: "Graduation Ceremony Pribadi Bilingual School",
  },
  {
    src: require("/public/assets/documentation/event/graduation_ceremony_pribadi_bilingual_school_2.jpg"),
    width: 3,
    height: 4,
    title: "Graduation Ceremony Pribadi Bilingual School",
  },
  {
    src: require("/public/assets/documentation/event/graduation_ceremony_pribadi_bilingual_school_3.jpg"),
    width: 3,
    height: 2,
    title: "Graduation Ceremony Pribadi Bilingual School",
  },
  {
    src: require("/public/assets/documentation/event/hakordia_jabar_2021.jpg"),
    width: 3,
    height: 2,
    title: "Hakordia Jabar 2021",
  },

  {
    src: require("/public/assets/documentation/event/let_it_lose_by_dhio.jpg"),
    width: 3,
    height: 2,
    title: "Let It Lose By Dhio",
  },
  {
    src: require("/public/assets/documentation/event/pembukaan_innovation_center_ITDRI.jpg"),
    width: 3,
    height: 2,
    title: "Pembukaan Innovation Center ITDRI",
  },
  {
    src: require("/public/assets/documentation/event/pembukaan_innovation_center_ITDRI_2.jpg"),
    width: 3,
    height: 2,
    title: "Pembukaan Innovation Center ITDRI",
  },
  {
    src: require("/public/assets/documentation/event/PLN_data_professional_MC_training.jpg"),
    width: 3,
    height: 2,
    title: "PLN x DATA Professional MC Training",
  },
  {
    src: require("/public/assets/documentation/event/PLN_data_group_negotiation_skill_training.jpg"),
    width: 3,
    height: 2,
    title: "PLN x Data Group Negotiation Skill Training",
  },
  {
    src: require("/public/assets/documentation/event/savaravat.jpg"),
    width: 3,
    height: 2,
    title: "Savaravat",
  },
  {
    src: require("/public/assets/documentation/event/tausyiah_kajian_bank_BJB.jpg"),
    width: 3,
    height: 2,
    title: "Tausyiah Kajian Bank BJB",
  },
];

export const graduationPhotos = [
  {
    src: "https://lh5.googleusercontent.com/d/1XbWyPE31_y8bUu2YyrpFktvQk-wzgH5C",
    width: 2,
    height: 3,
    title: "IPB - Amel",
  },
  {
    src: IPB_Amel,
    width: 3,
    height: 2,
    title: "IPB - Amel",
  },
  {
    src: require("/public/assets/documentation/graduation/IPDN_Ajeng.jpg"),
    width: 3,
    height: 2,
    title: "IPDN - Ajeng",
  },
  {
    src: require("/public/assets/documentation/graduation/IPDN_Mirfadhiyah.jpg"),
    width: 3,
    height: 2,
    title: "IPDN - Mirfadhiyah",
  },
  {
    src: require("/public/assets/documentation/graduation/Maranatha_Basaria.jpg"),
    width: 2,
    height: 3,
    title: "Maranatha - Basaria",
  },
  {
    src: require("/public/assets/documentation/graduation/Polban_Fathul.jpg"),
    width: 3,
    height: 2,
    title: "Polban - Fathul",
  },
  {
    src: require("/public/assets/documentation/graduation/Unisba.jpg"),
    width: 3,
    height: 2,
    title: "Unisba",
  },
  {
    src: require("/public/assets/documentation/graduation/Unisba_Alia.jpg"),
    width: 3,
    height: 2,
    title: "Unisba - Alia",
  },
  {
    src: require("/public/assets/documentation/graduation/Unisba_Alia_2.jpg"),
    width: 2,
    height: 3,
    title: "Unisba - Alia",
  },
  {
    src: require("/public/assets/documentation/graduation/Unjani_Sumdok_Nia.jpg"),
    width: 3,
    height: 2,
    title: "Unjani - Sumpah Dokter - Nia",
  },
  {
    src: require("/public/assets/documentation/graduation/Unpad_Grup_Session_Sumdok.jpg"),
    width: 2,
    height: 3,
    title: "Unpad - Sumpah Dokter",
  },
  {
    src: require("/public/assets/documentation/graduation/Unpad_Grup_Session.jpg"),
    width: 2,
    height: 3,
    title: "Unpad",
  },
  {
    src: require("/public/assets/documentation/graduation/Unpad_Ogy.jpg"),
    width: 3,
    height: 2,
    title: "Unpad - Ogy",
  },
  {
    src: require("/public/assets/documentation/graduation/Unpad_Regina.jpg"),
    width: 2,
    height: 3,
    title: "Unpad - Regina",
  },
  {
    src: require("/public/assets/documentation/graduation/Unpad_Rifat.jpg"),
    width: 2,
    height: 3,
    title: "Unpad - Rifat",
  },
  {
    src: require("/public/assets/documentation/graduation/Unpad_Rinaldy.jpg"),
    width: 2,
    height: 3,
    title: "Unpad - Rinaldy",
  },
  {
    src: require("/public/assets/documentation/graduation/Unpad_Syahla.jpg"),
    width: 2,
    height: 3,
    title: "Unpad - Syahla",
  },
  {
    src: require("/public/assets/documentation/graduation/Unpad_Vania.jpg"),
    width: 2,
    height: 3,
    title: "Unpad - Vania",
  },
  {
    src: require("/public/assets/documentation/graduation/Unpad_Zalikha.jpg"),
    width: 2,
    height: 3,
    title: "Unpad - Zalikha",
  },
  {
    src: require("/public/assets/documentation/graduation/UPI_Idvan.jpg"),
    width: 3,
    height: 2,
    title: "UPI - Idvan",
  },
  {
    src: require("/public/assets/documentation/graduation/UPI_Idvan_2.jpg"),
    width: 2,
    height: 3,
    title: "UPI - Idvan",
  },
  {
    src: require("/public/assets/documentation/graduation/UPI_Mayang.jpg"),
    width: 2,
    height: 3,
    title: "UPI - Mayang",
  },
  {
    src: require("/public/assets/documentation/graduation/UPI_Unpad.jpg"),
    width: 2,
    height: 3,
    title: "UPI - Unpad",
  },
];

export const birthdayPhotos = [
  {
    src: require("/public/assets/documentation/birthday/alyssa_mother_party.jpg"),
    width: 3,
    height: 2,
    title: "Alyssa Mother's Party",
  },
  {
    src: require("/public/assets/documentation/birthday/alyssa_mother_party_3.jpg"),
    width: 3,
    height: 2,
    title: "Alyssa Mother's Party",
  },

  {
    src: require("/public/assets/documentation/birthday/alyssa_mother_party_2.jpg"),
    width: 3,
    height: 2,
    title: "Alyssa Mother's Party",
  },
  {
    src: require("/public/assets/documentation/birthday/annasya_birthday_party.jpg"),
    width: 2,
    height: 3,
    title: "Annasya Birthday Party",
  },
  {
    src: require("/public/assets/documentation/birthday/alyssa_mother_party_3.jpg"),
    width: 3,
    height: 2,
    title: "Alyssa Mother's Party",
  },
  {
    src: require("/public/assets/documentation/birthday/annasya_birthday_party_2.jpg"),
    width: 2,
    height: 3,
    title: "Annasya Birthday Party",
  },
  {
    src: require("/public/assets/documentation/birthday/naira_birthday_party_6.jpg"),
    width: 3,
    height: 2,
    title: "Naira Birthday Party",
  },
  {
    src: require("/public/assets/documentation/birthday/naira_birthday_party_6.jpg"),
    width: 2,
    height: 2,
    title: "Naira Birthday Party",
  },
  {
    src: require("/public/assets/documentation/birthday/naira_birthday_party_7.jpg"),
    width: 3,
    height: 2,
    title: "Naira Birthday Party",
  },
  {
    src: require("/public/assets/documentation/birthday/alyssa_mother_party_7.jpg"),
    width: 3,
    height: 2,
    title: "Alyssa Mother's Party",
  },
  {
    src: require("/public/assets/documentation/birthday/annasya_birthday_party_3.jpg"),
    width: 2,
    height: 3,
    title: "Annasya Birthday Party",
  },
  {
    src: require("/public/assets/documentation/birthday/naira_birthday_party_5.jpg"),
    width: 3,
    height: 2,
    title: "Naira Birthday Party",
  },
  {
    src: require("/public/assets/documentation/birthday/annasya_birthday_party_4.jpg"),
    width: 3,
    height: 2,
    title: "Annasya Birthday Party",
  },
  {
    src: require("/public/assets/documentation/birthday/naira_birthday_party_4.jpg"),
    width: 3,
    height: 2,
    title: "Naira Birthday Party",
  },
  {
    src: require("/public/assets/documentation/birthday/naira_birthday_party.jpg"),
    width: 3,
    height: 2,
    title: "Naira Birthday Party",
  },
  {
    src: require("/public/assets/documentation/birthday/naira_birthday_party_2.jpg"),
    width: 3,
    height: 2,
    title: "Naira Birthday Party",
  },
  {
    src: require("/public/assets/documentation/birthday/naira_birthday_party_4.jpg"),
    width: 3,
    height: 2,
    title: "Naira Birthday Party",
  },
  {
    src: require("/public/assets/documentation/birthday/naira_birthday_party_3.jpg"),
    width: 2,
    height: 3,
    title: "Naira Birthday Party",
  },
];

export const engagementPhotos = [
  {
    src: require("/public/assets/documentation/engagement/engagement_of_syifadea_ilham_8.jpg"),
    width: 2,
    height: 3,
    title: "Engagement Of Syifadea Ilham",
  },
  {
    src: require("/public/assets/documentation/engagement/engagement_of_nadhila_adhil.jpg"),
    width: 3,
    height: 2,
    title: "Engagement Of Nadhila Adhil",
  },
  {
    src: require("/public/assets/documentation/engagement/engagement_of_nadhila_adhil_2.jpg"),
    width: 3,
    height: 2,
    title: "Engagement Of Nadhila Adhil",
  },
  {
    src: require("/public/assets/documentation/engagement/engagement_of_nadhila_adhil_3.jpg"),
    width: 3,
    height: 2,
    title: "Engagement Of Nadhila Adhil",
  },
  {
    src: require("/public/assets/documentation/engagement/engagement_of_nadhila_adhil_4.jpg"),
    width: 3,
    height: 2,
    title: "Engagement Of Nadhila Adhil",
  },
  {
    src: require("/public/assets/documentation/engagement/engagement_of_safitriyani_ramadhan.jpg"),
    width: 3,
    height: 2,
    title: "Engagement Of Safitriyani Ramadhan",
  },
  {
    src: require("/public/assets/documentation/engagement/engagement_of_safitriyani_ramadhan_2.jpg"),
    width: 3,
    height: 2,
    title: "Engagement Of Safitriyani Ramadhan",
  },
  {
    src: require("/public/assets/documentation/engagement/engagement_of_safitriyani_ramadhan_3.jpg"),
    width: 3,
    height: 2,
    title: "Engagement Of Safitriyani Ramadhan",
  },
  {
    src: require("/public/assets/documentation/engagement/engagement_of_syifadea_ilham_9.jpg"),
    width: 2,
    height: 3,
    title: "Engagement Of Syifadea Ilham",
  },
  {
    src: require("/public/assets/documentation/engagement/engagement_of_syifadea_ilham.jpg"),
    width: 3,
    height: 2,
    title: "Engagement Of Syifadea Ilham",
  },
  {
    src: require("/public/assets/documentation/engagement/engagement_of_syifadea_ilham_2.jpg"),
    width: 3,
    height: 2,
    title: "Engagement Of Syifadea Ilham",
  },
  {
    src: require("/public/assets/documentation/engagement/engagement_of_safitriyani_ramadhan_4.jpg"),
    width: 2,
    height: 3,
    title: "Engagement Of Safitriyani Ramadhan",
  },
  {
    src: require("/public/assets/documentation/engagement/engagement_of_syifadea_ilham_3.jpg"),
    width: 3,
    height: 2,
    title: "Engagement Of Syifadea Ilham",
  },
  {
    src: require("/public/assets/documentation/engagement/engagement_of_syifadea_ilham_7.jpg"),
    width: 2,
    height: 3,
    title: "Engagement Of Syifadea Ilham",
  },
  {
    src: require("/public/assets/documentation/engagement/engagement_of_syifadea_ilham_4.jpg"),
    width: 3,
    height: 2,
    title: "Engagement Of Syifadea Ilham",
  },
  {
    src: require("/public/assets/documentation/engagement/engagement_of_syifadea_ilham_5.jpg"),
    width: 3,
    height: 2,
    title: "Engagement Of Syifadea Ilham",
  },
  {
    src: require("/public/assets/documentation/engagement/engagement_of_syifadea_ilham_6.jpg"),
    width: 3,
    height: 2,
    title: "Engagement Of Syifadea Ilham",
  },
  {
    src: require("/public/assets/documentation/engagement/engagement_of_triah_robi.jpg"),
    width: 3,
    height: 2,
    title: "Engagement Of Triah Robi",
  },
  {
    src: require("/public/assets/documentation/engagement/engagement_of_triah_robi_2.jpg"),
    width: 3,
    height: 2,
    title: "Engagement Of Triah Robi",
  },
  {
    src: require("/public/assets/documentation/engagement/engagement_of_triah_robi_3.jpg"),
    width: 3,
    height: 2,
    title: "Engagement Of Triah Robi",
  },
  {
    src: require("/public/assets/documentation/engagement/engagement_of_triah_robi_4.jpg"),
    width: 3,
    height: 2,
    title: "Engagement Of Triah Robi",
  },
  {
    src: require("/public/assets/documentation/engagement/engagement_of_triah_robi_5.jpg"),
    width: 3,
    height: 2,
    title: "Engagement Of Triah Robi",
  },
  {
    src: require("/public/assets/documentation/engagement/engagement_of_triah_robi_6.jpg"),
    width: 3,
    height: 2,
    title: "Engagement Of Triah Robi",
  },
];

export const preweddingPhotos = [
  {
    src: require("/public/assets/documentation/prewedding/prewedding_in_UPI.jpg"),
    width: 2,
    height: 2,
    title: "Prewedding In UPI",
  },
  {
    src: require("/public/assets/documentation/prewedding/prewedding_of_ajeng_faisal.jpg"),
    width: 3,
    height: 2,
    title: "Prewedding Of Ajeng Faisal",
  },
  {
    src: require("/public/assets/documentation/prewedding/prewedding_of_ajeng_faisal_2.jpg"),
    width: 2,
    height: 2,
    title: "Prewedding Of Ajeng Faisal",
  },
  {
    src: require("/public/assets/documentation/prewedding/prewedding_of_ajeng_faisal_3.jpg"),
    width: 2,
    height: 3,
    title: "Prewedding Of Ajeng Faisal",
  },
  {
    src: require("/public/assets/documentation/prewedding/prewedding_of_azis_feby.jpg"),
    width: 3,
    height: 2,
    title: "Prewedding Of Azis Feby",
  },
  {
    src: require("/public/assets/documentation/prewedding/prewedding_of_ega_handoko.jpg"),
    width: 3,
    height: 2,
    title: "Prewedding Of Ega Handoko",
  },
  {
    src: require("/public/assets/documentation/prewedding/prewedding_of_ega_handoko_2.jpg"),
    width: 1,
    height: 2,
    title: "Prewedding Of Ega Handoko",
  },
  {
    src: require("/public/assets/documentation/prewedding/prewedding_of_ega_handoko_3.jpg"),
    width: 1,
    height: 2,
    title: "Prewedding Of Ega Handoko",
  },
  {
    src: require("/public/assets/documentation/prewedding/prewedding_of_ega_handoko_4.jpg"),
    width: 3,
    height: 2,
    title: "Prewedding Of Ega Handoko",
  },
  {
    src: require("/public/assets/documentation/prewedding/prewedding_of_ega_handoko_5.jpg"),
    width: 2,
    height: 2,
    title: "Prewedding Of Ega Handoko",
  },
  {
    src: require("/public/assets/documentation/prewedding/prewedding_of_safitriyani_ramadhan.jpg"),
    width: 2,
    height: 3,
    title: "Prewedding Of Safitriyani Ramadhan",
  },
  {
    src: require("/public/assets/documentation/prewedding/prewedding_of_safitriyani_ramadhan_2.jpg"),
    width: 3,
    height: 2,
    title: "Prewedding Of Safitriyani Ramadhan",
  },
  {
    src: require("/public/assets/documentation/prewedding/prewedding_of_tika_nova.jpg"),
    width: 2,
    height: 2,
    title: "Prewedding Of Tika Nova",
  },
  {
    src: require("/public/assets/documentation/prewedding/prewedding_of_tika_nova_2.jpg"),
    width: 2,
    height: 2,
    title: "Prewedding Of Tika Nova",
  },
  {
    src: require("/public/assets/documentation/prewedding/prewedding_of_tika_nova_3.jpg"),
    width: 3,
    height: 2,
    title: "Prewedding Of Tika Nova",
  },
  {
    src: require("/public/assets/documentation/prewedding/syifa_syahriel.jpg"),
    width: 3,
    height: 2,
    title: "Prewedding Of Syifa Syahriel",
  },
  {
    src: require("/public/assets/documentation/prewedding/syifa_syahriel_2.jpg"),
    width: 4,
    height: 2,
    title: "Prewedding Of Syifa Syahriel",
  },
  {
    src: require("/public/assets/documentation/prewedding/syifa_syahriel_3.jpg"),
    width: 2,
    height: 3,
    title: "Prewedding Of Syifa Syahriel",
  },
  {
    src: require("/public/assets/documentation/prewedding/syifa_syahriel_4.jpg"),
    width: 3,
    height: 2,
    title: "Prewedding Of Syifa Syahriel",
  },
];

export const siramanPhotos = [
  {
    src: require("/public/assets/documentation/siraman/siraman_chyntia.jpg"),
    width: 2,
    height: 2,
    title: "Siraman Chyntia",
  },
  {
    src: require("/public/assets/documentation/siraman/siraman_chyntia_2.jpg"),
    width: 3,
    height: 2,
    title: "Siraman Chyntia",
  },
  {
    src: require("/public/assets/documentation/siraman/siraman_chyntia_3.jpg"),
    width: 3,
    height: 2,
    title: "Siraman Chyntia",
  },
  {
    src: require("/public/assets/documentation/siraman/siraman_chyntia_4.jpg"),
    width: 2,
    height: 2,
    title: "Siraman Chyntia",
  },
  {
    src: require("/public/assets/documentation/siraman/siraman_chyntia_5.jpg"),
    width: 3,
    height: 2,
    title: "Siraman Chyntia",
  },
  {
    src: require("/public/assets/documentation/siraman/siraman_chyntia_6.jpg"),
    width: 3,
    height: 2,
    title: "Siraman Chyntia",
  },
  {
    src: require("/public/assets/documentation/siraman/siraman_chyntia_7.jpg"),
    width: 3,
    height: 3,
    title: "Siraman Chyntia",
  },
  {
    src: require("/public/assets/documentation/siraman/siraman_chyntia_8.jpg"),
    width: 3,
    height: 2,
    title: "Siraman Chyntia",
  },
  {
    src: require("/public/assets/documentation/siraman/siraman_tika_4.jpg"),
    width: 2,
    height: 3,
    title: "Siraman Tika",
  },
  {
    src: require("/public/assets/documentation/siraman/siraman_chyntia_10.jpg"),
    width: 3,
    height: 2,
    title: "Siraman Chyntia",
  },
  {
    src: require("/public/assets/documentation/siraman/siraman_chyntia_11.jpg"),
    width: 3,
    height: 2,
    title: "Siraman Chyntia",
  },
  {
    src: require("/public/assets/documentation/siraman/siraman_chyntia_9.jpg"),
    width: 2,
    height: 3,
    title: "Siraman Chyntia",
  },
  {
    src: require("/public/assets/documentation/siraman/siraman_tika.jpg"),
    width: 2,
    height: 2,
    title: "Siraman Tika",
  },
  {
    src: require("/public/assets/documentation/siraman/siraman_tika_2.jpg"),
    width: 3,
    height: 2,
    title: "Siraman Tika",
  },
  {
    src: require("/public/assets/documentation/siraman/siraman_tika_3.jpg"),
    width: 3,
    height: 2,
    title: "Siraman Tika",
  },
  {
    src: require("/public/assets/documentation/siraman/siraman_tika_5.jpg"),
    width: 3,
    height: 2,
    title: "Siraman Tika",
  },
  {
    src: require("/public/assets/documentation/siraman/siraman_tika_6.jpg"),
    width: 2,
    height: 2,
    title: "Siraman Tika",
  },
  {
    src: require("/public/assets/documentation/siraman/siraman_tika_7.jpg"),
    width: 3,
    height: 2,
    title: "Siraman Tika",
  },
  {
    src: require("/public/assets/documentation/siraman/siraman_tika_8.jpg"),
    width: 3,
    height: 2,
    title: "Siraman Tika",
  },
  {
    src: require("/public/assets/documentation/siraman/siraman_tika_9.jpg"),
    width: 3,
    height: 2,
    title: "Siraman Tika",
  },
  {
    src: require("/public/assets/documentation/siraman/siraman_tika_10.jpg"),
    width: 3,
    height: 2,
    title: "Siraman Tika",
  },
];

export const weddingPhotos = [
  {
    src: require("/public/assets/documentation/wedding/wedding_feni_ekky.jpg"),
    width: 2,
    height: 2,
    title: "Wedding Feni Ekky",
  },
  {
    src: require("/public/assets/documentation/wedding/wedding_feni_ekky_2.jpg"),
    width: 3,
    height: 2,
    title: "Wedding Feni Ekky",
  },
  {
    src: require("/public/assets/documentation/wedding/wedding_of_resty_rizky.jpg"),
    width: 2,
    height: 3,
    title: "Wedding Resty Rezky",
  },
  {
    src: require("/public/assets/documentation/wedding/wedding_of_resty_rizky_2.jpg"),
    width: 2,
    height: 3,
    title: "Wedding Resty Rezky",
  },
  {
    src: require("/public/assets/documentation/wedding/wedding_of_resty_rizky_3.jpg"),
    width: 2,
    height: 2,
    title: "Wedding Resty Rezky",
  },
  {
    src: require("/public/assets/documentation/wedding/wedding_of_resty_rizky_4.jpg"),
    width: 3,
    height: 2,
    title: "Wedding Resty Rezky",
  },
  {
    src: require("/public/assets/documentation/wedding/wedding_of_resty_rizky_5.jpg"),
    width: 2,
    height: 3,
    title: "Wedding Resty Rezky",
  },
  {
    src: require("/public/assets/documentation/wedding/wedding_of_safitriyani_ramadhan.jpg"),
    width: 3,
    height: 2,
    title: "Wedding Safitriyani Ramadhan",
  },
  {
    src: require("/public/assets/documentation/wedding/wedding_of_safitriyani_ramadhan_2.jpg"),
    width: 3,
    height: 2,
    title: "Wedding Safitriyani Ramadhan",
  },
  {
    src: require("/public/assets/documentation/wedding/wedding_of_safitriyani_ramadhan_3.jpg"),
    width: 2,
    height: 2,
    title: "Wedding Safitriyani Ramadhan",
  },
  {
    src: require("/public/assets/documentation/wedding/wedding_of_selly_wawan.jpg"),
    width: 2,
    height: 2,
    title: "Wedding Selly Wawan",
  },
  {
    src: require("/public/assets/documentation/wedding/wedding_of_selly_wawan_2.jpg"),
    width: 2,
    height: 3,
    title: "Wedding Selly Wawan",
  },
  {
    src: require("/public/assets/documentation/wedding/wedding_of_sera_alie.jpg"),
    width: 2,
    height: 3,
    title: "Wedding Sera Alie",
  },
  {
    src: require("/public/assets/documentation/wedding/wedding_of_sera_alie_2.jpg"),
    width: 2,
    height: 2,
    title: "Wedding Sera Alie",
  },
  {
    src: require("/public/assets/documentation/wedding/wedding_of_sera_alie_3.jpg"),
    width: 2,
    height: 2,
    title: "Wedding Sera Alie",
  },
  {
    src: require("/public/assets/documentation/wedding/wedding_of_sera_alie_4.jpg"),
    width: 2,
    height: 2,
    title: "Wedding Sera Alie",
  },
  {
    src: require("/public/assets/documentation/wedding/wedding_of_ulfie_raka.jpg"),
    width: 2,
    height: 2,
    title: "Wedding Ulfie Raka",
  },
  {
    src: require("/public/assets/documentation/wedding/wedding_of_ulfie_raka_2.jpg"),
    width: 3,
    height: 2,
    title: "Wedding Ulfie Raka",
  },
  {
    src: require("/public/assets/documentation/wedding/wedding_of_ulfie_raka_3.jpg"),
    width: 2,
    height: 2,
    title: "Wedding Ulfie Raka",
  },
  {
    src: require("/public/assets/documentation/wedding/wedding_of_ulfie_raka_4.jpg"),
    width: 2,
    height: 2,
    title: "Wedding Ulfie Raka",
  },
  {
    src: require("/public/assets/documentation/wedding/wedding_tika_nova.jpg"),
    width: 3,
    height: 2,
    title: "Wedding Tika Nova",
  },
  {
    src: require("/public/assets/documentation/wedding/wedding_tika_nova_2.jpg"),
    width: 2,
    height: 2,
    title: "Wedding Tika Nova",
  },
  {
    src: require("/public/assets/documentation/wedding/wedding_tika_nova_3.jpg"),
    width: 2,
    height: 3,
    title: "Wedding Tika Nova",
  },
];
